Repository airbnb-clone-project/Frontend, pull requests merged in 2024-12, with the labels that each got.

#11 [Style] 핀 만들기 page 마크업
  src/components/@Modal/BoardSelectModal.tsx
  src/components/@Modal/createPinEdit/BoardSectionSelect.tsx
  src/components/@Modal/thisPinEdit/BoardSelector.tsx
  src/components/common/Input.tsx
  src/components/common/LabelInput.tsx
  src/components/common/TransparentButton.tsx
  src/components/icons/CheckIcon.tsx
  src/components/icons/DoubleLeftArrowIcon.tsx
  src/components/icons/DoubleRightArrowIcon.tsx
  src/components/icons/MinusIcon.tsx
  src/components/icons/PlusBGIcon.tsx
  src/components/icons/ThreeDotIcon.tsx
  src/components/icons/UpArrowBGIcon.tsx
  src/hooks/pinCreate/useBoardSelect.ts
  src/hooks/pinCreate/useOptionSettings.ts
  src/hooks/pinCreate/usePinForm.ts
  src/hooks/pinCreate/usePinList.ts
  src/hooks/pinCreate/useTagSearch.ts
  src/pages/create/Create.tsx
  src/pages/create/components/index.tsx
  src/pages/pinCreate/PinCreate.tsx
  src/pages/pinCreate/components/BoardSelectBox.tsx
  src/pages/pinCreate/components/ImgInput.tsx
  src/pages/pinCreate/components/PinExplainInput.tsx
  src/pages/pinCreate/components/SearchResult.tsx
  src/pages/pinCreate/components/SideBar.tsx
  src/pages/pinCreate/components/TagList.tsx
  src/router.tsx
  tailwind.config.js
Labels: style💄

#10 [Feat] 핀 상세페이지 제작 및 리팩토링
  package.json
  src/.prettierrc
  src/constants/helperText.ts
  src/main.tsx
  src/pages/App.tsx
  src/pages/home.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/pinDetail/PinDetail.tsx
  src/pages/pinDetail/source/__mock__/imgData.ts
  src/pages/pinDetail/source/__mock__/index.ts
  src/pages/pinDetail/source/animations/gsapPlugins.ts
  src/pages/pinDetail/source/animations/index.ts
  src/pages/pinDetail/source/animations/pinAnimation.ts
  src/pages/pinDetail/source/components/CreatorBox.tsx
  src/pages/pinDetail/source/components/PinDetailNav.tsx
  src/pages/pinDetail/source/components/buttons/AnswerBtn.tsx
  src/pages/pinDetail/source/components/buttons/BackBtn.tsx
  src/pages/pinDetail/source/components/buttons/CommentHeartBtn.tsx
  src/pages/pinDetail/source/components/buttons/CommentOptionsBtn.tsx
  src/pages/pinDetail/source/components/buttons/FollowBtn.tsx
  src/pages/pinDetail/source/components/buttons/HeartBtn.tsx
  src/pages/pinDetail/source/components/buttons/ImageSearchBtn.tsx
  src/pages/pinDetail/source/components/buttons/ImageZoomBtn.tsx
  src/pages/pinDetail/source/components/buttons/MyBoardBtn.tsx
  src/pages/pinDetail/source/components/buttons/OptionsBtn.tsx
  src/pages/pinDetail/source/components/buttons/SaveBtn.tsx
  src/pages/pinDetail/source/components/buttons/SendBtn.tsx
  src/pages/pinDetail/source/components/buttons/ShareBtn.tsx
  src/pages/pinDetail/source/components/comment/AnswerBox.tsx
  src/pages/pinDetail/source/components/comment/Comment.tsx
  src/pages/pinDetail/source/components/comment/CommentBox.tsx
  src/pages/pinDetail/source/components/comment/CommentInput.tsx
  src/pages/pinDetail/source/components/comment/NoComment.tsx
  src/pages/pinDetail/source/components/common/Button.tsx
  src/pages/pinDetail/source/components/common/Input.tsx
  src/pages/pinDetail/source/components/common/Portal.tsx
  src/pages/pinDetail/source/components/modals/ImageZoomModal.tsx
  src/pages/pinDetail/source/components/modals/OptionsModal.tsx
  src/pages/pinDetail/source/container/PinDetailSection.tsx
  src/pages/pinDetail/source/hooks/index.ts
  src/pages/pinDetail/source/hooks/usePinDetailEffect.ts
  src/pages/pinDetail/source/hooks/usePinDetailGSAP.ts
  src/pages/pinDetail/source/utils/handleImageLoad.ts
  src/pages/pinDetail/source/utils/index.ts
  src/router.tsx
  src/services/client.ts
  src/services/getUser.ts
  tailwind.config.js
  yarn.lock
Labels: feat✨, refactor♻️, style💄

#13 [Feat] img 업로드시 preview기능
  src/hooks/pinCreate/usePinForm.ts
  src/pages/pinCreate/PinCreate.tsx
  src/pages/pinCreate/components/ImgInput.tsx
Labels: feat✨

#15 [Feat] 핀 초안 item 삭제
  src/components/icons/TrashIcon.tsx
  src/pages/pinCreate/PinCreate.tsx
  src/pages/pinCreate/components/BoardSelectBox.tsx
  src/pages/pinCreate/components/DraftDeleteModal.tsx
  src/pages/pinCreate/components/PinDraftList.tsx
  src/pages/pinCreate/components/SideBar.tsx
  src/pages/pinCreate/components/TagList.tsx
  src/stores/useModalStore.tsx
  src/types/modalName.ts
Labels: feat✨

#21 [ Feat] 로그인 및 회원가입 기능 (Guest-view 페이지)
  .yarn/install-state.gz
  package.json
  src/components/@Bar/headerbar/HeaderBar.tsx
  src/components/@Bar/headerbar/focusmodal/FocusModal.tsx
  src/components/@Bar/helpbar/HelpBar.tsx
  src/components/@Bar/sidebar/SideBar.tsx
  src/components/@Bar/sidebar/hovermodal/HoverModal.tsx
  src/components/@Bar/sidebar/icon/Icon.tsx
  src/components/@Modal/ModalLayout.tsx
  src/components/@Modal/auth/loginModal/LoginModal.tsx
  src/components/@Modal/auth/signupModal/SignupForm.tsx
  src/components/@Modal/auth/signupModal/SignupModal.tsx
  src/components/common/AppBtn.tsx
  src/components/common/AuthInput.tsx
  src/components/common/GoogleBtn.tsx
  src/constants/messages.ts
  src/hooks/useOverlayHook.ts
  src/main.tsx
  src/pages/App.tsx
  src/pages/guest/Guest.tsx
  src/pages/guest/source/components/GuestHeader.tsx
  src/pages/home/Home.tsx
  src/pages/home/source/__mock__/index.ts
  src/pages/home/source/__mock__/pinData.ts
  src/pages/main/Main.tsx
  src/pages/main/components/73_20200831140305.png
  src/pages/main/components/common/Button.tsx
  src/pages/main/components/imagebox/ImageBox.tsx
  src/pages/main/components/imagebox/overlay/Overlay.tsx
  src/pages/main/components/imagebox/overlay/overlaybottom/OverlayBottom.tsx
  src/pages/main/components/imagebox/overlay/overlaybottom/OverlayBottomIcon.tsx
  src/pages/main/components/imagebox/overlay/overlayheader/OverlayHeader.tsx
  src/pages/main/components/modal/profilemodal/BoardRow.tsx
  src/pages/main/components/modal/profilemodal/ProfileModal.tsx
  src/pages/main/components/modal/recommendmodal/RecommendModal.tsx
  src/pages/main/components/showimages/ShowImages.tsx
  src/pages/main/components/김마야님_배경투명화.png
  src/pages/main/components/윙푸님_투명배경.png
  src/pages/pinDetail/source/animations/index.ts
  src/pages/pinDetail/source/container/PinDetailSection.tsx
  src/router.tsx
  src/services/client.ts
  src/services/getPins.ts
  src/services/types/pin.d.ts
  src/stores/authStore.ts
  src/stores/useIconStore.ts
  src/stores/useModalStore.ts
  src/types/modalName.ts
  src/types/overlayName.ts
  src/utils/gsapPlugins.ts
  src/utils/index.ts
  src/utils/schemas/user-schema.ts
  tailwind.config.js
  vite.config.ts
  yarn.lock
Labels: feat✨, style💄

#22 [Feat] 특정 요소 외의 click 감지 후 callback 함수 실행 hook
  src/components/icons/DoubleRightArrowIcon.tsx
  src/hooks/useDynamicPosition.ts
  src/hooks/useOutsideClick.ts
  src/pages/pinCreate/components/BoardSelectBox.tsx
  src/pages/pinCreate/components/PinDraftList.tsx
  src/pages/pinCreate/components/SideBar.tsx
  src/router.tsx
  src/types/modalName.ts
  yarn.lock
Labels: feat✨
