Repository airbnb-clone-project/Frontend, pull requests merged in 2025-02, with the labels that each got.

#46 [Refactor] 메인 페이지 Masonry 레이아웃 구현 및 컴포넌트
  package.json
  src/components/@Modal/messageBoard/Chat.tsx
  src/components/@Modal/messageBoard/MessageBoard.tsx
  src/components/common/Pin/PinImage.tsx
  src/components/common/Spinner.tsx
  src/constants/queryKey.ts
  src/pages/main/Main.tsx
  src/pages/main/source/components/@Modal/profilemodal/ProfileModal.tsx
  src/pages/main/source/components/@Modal/recommendmodal/RecommendModal.tsx
  src/pages/main/source/components/BoardModal/BoardRow.tsx
  src/pages/main/source/components/BoardModal/ProfileModal.tsx
  src/pages/main/source/components/ImageBox/index.tsx
  src/pages/main/source/components/Overlay/Bottom.tsx
  src/pages/main/source/components/Overlay/BottomIcon.tsx
  src/pages/main/source/components/Overlay/Header.tsx
  src/pages/main/source/components/Overlay/index.tsx
  src/pages/main/source/components/Pin/PinImage.tsx
  src/pages/main/source/components/Pin/PinOverlay.tsx
  src/pages/main/source/components/Pin/index.tsx
  src/pages/main/source/components/ShowImages/index.tsx
  src/pages/main/source/constants/layout.ts
  src/pages/main/source/container/MainContainer.tsx
  src/pages/main/source/types/masonry.d.ts
  yarn.lock
Labels: chore 🩹, feat✨, refactor♻️

#47 [Refactor] 전체적인 파일 리팩토링 & 병합
  package.json
  src/components/@Modal/auth/signupModal/SignupForm.tsx
  src/components/@Modal/createPinEdit/CreatePinEditModal.tsx
  src/components/@Modal/messageBoard/Chat.tsx
  src/components/@Modal/modal.tsx
  src/components/@Modal/tempPinEdit/TempPinEditModal.tsx
  src/components/common/Input.tsx
  src/components/common/LabelInput.tsx
  src/components/common/WarningText.tsx
  src/components/common/button.tsx
  src/components/common/index.tsx
  src/components/icons/InfoIcon.tsx
  src/components/icons/PwHideIcon.tsx
  src/components/icons/PwShowIcon.tsx
  src/constants/index.ts
  src/hooks/index.ts
  src/hooks/pin/useCurrentPin.ts
  src/hooks/pin/useTempPinList.ts
  src/hooks/queries/usePinEdit.ts
  src/hooks/queries/usePostPin.ts
  src/hooks/queries/useTempPinCopy.ts
  src/hooks/queries/useTempPinDelete.ts
  src/hooks/queries/useTempPinUpdate.ts
  src/layouts/sidebar/source/components/MessageModal.tsx
  src/layouts/sidebar/source/components/chat/ChatRoom.tsx
  src/pages/accountManagement/AccountManagement.tsx
  src/pages/accountManagement/components/Footer.tsx
  src/pages/accountManagement/components/MyAccount.tsx
  src/pages/accountManagement/components/PrivacySetting.tsx
  src/pages/accountManagement/components/privacySetting/Birth.tsx
  src/pages/accountManagement/components/privacySetting/Calendar.tsx
  src/pages/accountManagement/components/privacySetting/Country.tsx
  src/pages/accountManagement/components/privacySetting/Language.tsx
  src/pages/accountManagement/components/privacySetting/Sexual.tsx
  src/pages/mypage/components/Created.tsx
  src/pages/pinCreate/PinCreate.tsx
  src/pages/pinCreate/components/PinDraftList.tsx
  src/pages/pinCreate/components/SideBar.tsx
  src/pages/profileEdit/ProfileEdit.tsx
  src/pages/setting/Setting.tsx
  src/pages/setting/components/MenuNav.tsx
  src/router.tsx
  src/services/auth/getUser.ts
  src/services/auth/getUserProfile.ts
  src/services/chat/chat.ts
  src/services/chat/chatTest.ts
  src/services/client.ts
  src/services/pin/deleteTempPin.ts
  src/services/pin/getMyPinsCheck.ts
  src/services/pin/getPins.ts
  src/services/pin/getTempsPinCheck.ts
  src/services/pin/postCreatePin.ts
  src/services/pin/postPinPost.ts
  src/services/pin/postTempPinCopy.ts
  src/services/pin/postTempPinCreate.ts
  src/services/pin/putPinEdit.ts
  src/services/pin/putTempPinEdit.ts
  src/stores/index.ts
  src/types/type.ts
  yarn.lock
Labels: refactor♻️

#48 [Style] 프로필 수정, 계정 관리 page 마크업
  src/components/icons/CalendarIcon.tsx
  src/pages/accountManagement/AccountManagement.tsx
  src/pages/accountManagement/components/privacySetting/Birth.tsx
  src/pages/accountManagement/components/privacySetting/Calendar.tsx
  src/pages/accountManagement/components/privacySetting/css/Calendar.css
  src/pages/profileEdit/ProfileEdit.tsx
  src/pages/profileEdit/components/Footer.tsx
  src/pages/profileEdit/components/Introduce.tsx
  src/pages/profileEdit/components/Name.tsx
  src/pages/profileEdit/components/Picture.tsx
  src/pages/profileEdit/components/UserName.tsx
  src/pages/profileEdit/components/WebSite.tsx
  src/pages/setting/Setting.tsx
  src/pages/setting/components/MenuNav.tsx
Labels: feat✨, style💄

#51 [Feat] 비밀번호 변경 modal 마크업
  src/components/@Modal/pwChange/PwChangeModal.tsx
  src/components/@Modal/pwChange/components/CurrentPw.tsx
  src/components/@Modal/pwChange/components/Footer.tsx
  src/components/@Modal/pwChange/components/NewPw.tsx
  src/components/@Modal/pwChange/components/NewPwCheck.tsx
  src/components/common/LabelInput.tsx
  src/hooks/auth/useIsPwHide.ts
  src/pages/accountManagement/AccountManagement.tsx
  src/pages/accountManagement/components/Footer.tsx
  src/pages/accountManagement/components/MyAccount.tsx
  src/pages/accountManagement/components/privacySetting/Birth.tsx
  src/types/modalName.ts
Labels: feat✨, style💄

#53 [Style] 이메일 인증 modal 마크업
  src/components/@Modal/emailVerification/EmailVerificationModal.tsx
  src/pages/accountManagement/AccountManagement.tsx
  src/pages/accountManagement/components/Footer.tsx
  src/types/modalName.ts
Labels: feat✨, style💄

#55 [Feat] Toast 애니메이션
  src/components/common/AnimatedToast.tsx
  src/pages/App.tsx
  src/pages/accountManagement/AccountManagement.tsx
  src/stores/useToastStore.ts
Labels: feat✨, style💄

#57 [Refactor]: 경고 문구 리팩토링
  src/components/@Modal/boardCreate/NameInput.tsx
  src/components/@Modal/boardEdit/NameInput.tsx
Labels: refactor♻️
